import { Component } from '@angular/core';

@Component({
  selector: 'app-privacy',
  standalone: true,
  template: `
    <div class="min-h-screen py-20 px-8 max-w-3xl mx-auto" style="color: var(--text-color)">
        <h1 class="text-4xl font-black mb-6">Privacy Policy</h1>
        <p class="mb-10 opacity-50 text-sm">Last Updated: April 2026</p>
        
        <div class="space-y-8">
            <section>
                <h2 class="text-xl font-bold mb-3">1. Information We Collect</h2>
                <p class="text-sm opacity-80 leading-relaxed mb-4">
                    When you register and use Scout, we collect your email address, profile information, and authentication 
                    data. We also store records of the domain queries you run, generated reports, and your credit balance.
                </p>
            </section>

            <section>
                <h2 class="text-xl font-bold mb-3">2. How We Use Third-Party Tools</h2>
                <p class="text-sm opacity-80 leading-relaxed">
                    To generate detailed domain analysis, your requested domain names are transmitted to third-party services 
                    we partner with, including SEO tool APIs (like Ahrefs/Majestic) and historical archives (like Wayback Machine). 
                    No personally identifiable information (PII) is explicitly sent to these services along with your domain queries.
                </p>
            </section>

            <section>
                <h2 class="text-xl font-bold mb-3">3. Data Security & Storage</h2>
                <p class="text-sm opacity-80 leading-relaxed">
                    Your data is securely stored within our infrastructure (powered by Supabase). We do not sell your personal 
                    information to third parties. Analysis reports generated by users may be cached to improve system performance 
                    and reduce API querying costs.
                </p>
            </section>
        </div>
    </div>
  `
})
export class PrivacyComponent {}
